#!/bin/bash

echo -ne "Content-type:text/plain\n\n"

# env
# cat -
set -f  # disable wildcard expansion
query=(${QUERY_STRING//[=&]/ })
set +f  # restore wildcard expansion
# echo "${query[@]}"

if [[ "${query[0]}" == "ask" && "${query[1]}" == "how%20do%20i%20get%20work%20done" ]]; then
	echo "HELL IS FULL"
	echo "MANKIND IS DEAD"
	echo "SPITE IS FUEL"
fi

